#!/bin/bash
if [ -z "$1" ]; then
    echo "Usage: $0 component-name [component-parameters-name=component-parameters-value ...]"
    exit 1
fi

image=$1
envs=""
shift
for var in "$@"
do
    envs="${envs} --env ${var}"
done

if [ -z ${CLAIMED_DATA_PATH+x} ]; then
  echo "CLAIMED_DATA_PATH variable not set, not mounting /data to the CLAIMED component"
  docker run -it $envs romeokienzler/$image
else
  echo "CLAIMED_DATA_PATH variable is set, mounting $CLAIMED_DATA_PATH to /data"
  docker run -it $envs -v `echo $CLAIMED_DATA_PATH`:/data/ romeokienzler/$image
fi
